/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Miguel
 */

public class TallerBBDD extends javax.swing.JFrame {
    
    public String x;

    


    /**
     * Creates new form TallerBBDD
     */
    public TallerBBDD() {
        initComponents();
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        titulo = new java.awt.Label();
        codigoTexto = new java.awt.Label();
        codigo = new javax.swing.JTextField();
        nombreTexto = new java.awt.Label();
        nombre = new javax.swing.JTextField();
        nacimientoTexto = new java.awt.Label();
        masculino = new javax.swing.JRadioButton();
        femenino = new javax.swing.JRadioButton();
        carreraTexto = new java.awt.Label();
        carrera = new javax.swing.JComboBox<>();
        botones = new java.awt.Panel();
        insertar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        intereses = new java.awt.Label();
        checkbox = new java.awt.Panel();
        lectura = new java.awt.Checkbox();
        deportes = new java.awt.Checkbox();
        danza = new java.awt.Checkbox();
        musica = new java.awt.Checkbox();
        teatro = new java.awt.Checkbox();
        videojuegos = new java.awt.Checkbox();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PROYECTO FINAL POO 2");
        setResizable(false);

        titulo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        titulo.setText("TALLER BASE DE DATOS CON MYSQL");

        codigoTexto.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        codigoTexto.setName(""); // NOI18N
        codigoTexto.setText("CÓDIGO:");

        codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoActionPerformed(evt);
            }
        });

        nombreTexto.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        nombreTexto.setName("nombre"); // NOI18N
        nombreTexto.setText("NOMBRE:");

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        nacimientoTexto.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        nacimientoTexto.setText("FECHA NACIMIENTO:");

        buttonGroup1.add(masculino);
        masculino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        masculino.setText("MASCULINO");

        buttonGroup1.add(femenino);
        femenino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        femenino.setText("FEMENINO");

        carreraTexto.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        carreraTexto.setName("nombre"); // NOI18N
        carreraTexto.setText("CARRERA:");

        carrera.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        carrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE CARRERA", "CARRERA 1", "CARRERA 2", "CARRERA 3", "CARRERA 4" }));
        carrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carreraActionPerformed(evt);
            }
        });

        botones.setLayout(new java.awt.GridLayout(0, 1, 0, 20));

        insertar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        insertar.setText("INSERTAR");
        insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarActionPerformed(evt);
            }
        });
        botones.add(insertar);

        modificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        modificar.setText("MODIFICAR");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        botones.add(modificar);

        eliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eliminar.setText("ELIMINAR");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        botones.add(eliminar);

        buscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buscar.setText("BUSCAR");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        botones.add(buscar);

        limpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        limpiar.setText("LIMPIAR");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        botones.add(limpiar);

        intereses.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        intereses.setText("INTERESES (Opcional)");

        checkbox.setLayout(new java.awt.GridLayout(2, 0));

        lectura.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lectura.setLabel("LECTURA");
        lectura.setName("lectura"); // NOI18N
        checkbox.add(lectura);

        deportes.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        deportes.setLabel("DEPORTES");
        deportes.setName("DEPORTES"); // NOI18N
        checkbox.add(deportes);

        danza.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        danza.setLabel("DANZA");
        checkbox.add(danza);

        musica.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        musica.setLabel("MÚSICA");
        checkbox.add(musica);

        teatro.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        teatro.setLabel("TEATRO");
        checkbox.add(teatro);

        videojuegos.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        videojuegos.setLabel("VIDEOJUEGOS");
        checkbox.add(videojuegos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(intereses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(masculino)
                                    .addComponent(carreraTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(femenino)
                                        .addGap(95, 95, 95))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(codigo)
                                                .addComponent(nombre)
                                                .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                                            .addComponent(carrera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(nacimientoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(botones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nacimientoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(masculino))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(femenino)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(carreraTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(codigoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botones, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(intereses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        codigoTexto.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        try{
            Connection conexion = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/ejercicioSwing", // URL BD
                "root",  // usuario de MySQL
                ""   // contraseña de MySQL
            );

            Statement stmt = conexion.createStatement();

            // Convertir fecha a formato SQL yyyy-MM-dd
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
            String fecha = sdf.format(jDateChooser1.getDate());


            String genero = "";
            if (masculino.isSelected()) {
                genero = masculino.getText();
            } else if (femenino.isSelected()) {
                genero = femenino.getText();
            }
            String intereses = "";

            if (lectura.getState()) {
                intereses += "lectura, ";
            }
            if (deportes.getState()) {
                intereses += "deportes, ";
            }
            if (danza.getState()) {
                intereses += "danza, ";
            }
            if (musica.getState()) {
                intereses += "musica, ";
            }
            if (teatro.getState()) {
                intereses += "teatro, ";
            }
            if (videojuegos.getState()) {
                intereses += "videojuegos, ";
            }
            if (!"".equals(intereses)){
                intereses=intereses.substring(0, intereses.length()-2);
            }
            

            System.out.println(genero);
            // Construir la consulta con concatenación
            String sql = "UPDATE estudiante SET " +
             "nombre = '" + nombre.getText() + "', " +
             "fecha = '" + fecha + "', " +
             "genero = '" + genero + "', " +
             "carrera = " + carrera.getSelectedIndex() + ", " +
             "intereses = '" + intereses + "' " +
             "WHERE codigo = " + codigo.getText() + ";";
            
                    
            stmt.executeUpdate(sql);
  
            conexion.close();
        } catch (Exception e){
            e.printStackTrace();
        }

    }//GEN-LAST:event_modificarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        x= codigo.getText();
        System.out.println(x);
        try{
            Connection conexion = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/ejercicioSwing", // URL BD
                "root",  // usuario de MySQL
                ""   // contraseña de MySQL
            );
            System.out.println("Conexion establecida");
            Statement stmt = conexion.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM estudiante WHERE codigo="+x+"");
            
            while (rs.next()){
                codigo.setText(rs.getString("codigo"));
                nombre.setText(rs.getString("nombre"));
                java.sql.Date sqlDate = rs.getDate("fecha");
                if (sqlDate != null) {
                    jDateChooser1.setDate(new java.util.Date(sqlDate.getTime()));
                }
                if (rs.getString("genero").equals("MASCULINO")) {
                    masculino.setSelected(true);
                } else if (rs.getString("genero").equals("FEMENINO")) {
                    femenino.setSelected(true);
                }
                carrera.setSelectedIndex(rs.getInt("carrera"));
                if (rs.getString("intereses").contains("lectura")) {
                    lectura.setState(true);
                } else {
                    lectura.setState(false);
                }

                if (rs.getString("intereses").contains("deportes")) {
                    deportes.setState(true);
                } else {
                    deportes.setState(false);
                }

                if (rs.getString("intereses").contains("danza")) {
                    danza.setState(true);
                } else {
                    danza.setState(false);
                }

                if (rs.getString("intereses").contains("musica")) {
                    musica.setState(true);
                } else {
                    musica.setState(false);
                }

                if (rs.getString("intereses").contains("teatro")) {
                    teatro.setState(true);
                } else {
                    teatro.setState(false);
                }

                if (rs.getString("intereses").contains("videojuegos")) {
                    videojuegos.setState(true);
                } else {
                    videojuegos.setState(false);
                }

                

            }
            conexion.close();
        } catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
        codigo.setText(null);
        nombre.setText(null);
        jDateChooser1.setDate(null);
        carrera.setSelectedIndex(0);
        buttonGroup1.clearSelection();
        lectura.setState(false);
        deportes.setState(false);
        danza.setState(false);
        musica.setState(false);
        teatro.setState(false);
        videojuegos.setState(false);
        
        
    }//GEN-LAST:event_limpiarActionPerformed

    
    
    
    private void insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarActionPerformed
        // TODO add your handling code here:
        
        try{
            Connection conexion = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/ejercicioSwing", // URL BD
                "root",  // usuario de MySQL
                ""   // contraseña de MySQL
            );

            Statement stmt = conexion.createStatement();

            // Convertir fecha a formato SQL yyyy-MM-dd
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
            String fecha = sdf.format(jDateChooser1.getDate());


            String genero = "";
            if (masculino.isSelected()) {
                genero = masculino.getText();
            } else if (femenino.isSelected()) {
                genero = femenino.getText();
            }
            
            String intereses = "";

            if (lectura.getState()) {
                intereses += "lectura, ";
            }
            if (deportes.getState()) {
                intereses += "deportes, ";
            }
            if (danza.getState()) {
                intereses += "danza, ";
            }
            if (musica.getState()) {
                intereses += "musica, ";
            }
            if (teatro.getState()) {
                intereses += "teatro, ";
            }
            if (videojuegos.getState()) {
                intereses += "videojuegos, ";
            }
            if (intereses!=""){
                intereses=intereses.substring(0, intereses.length()-2);
            }
            

            // Construir la consulta con concatenación
            String sql = "INSERT INTO estudiante (id, codigo, nombre, fecha, genero, carrera, intereses) VALUES (" 
                    + codigo.getText() + ", '" 
                    + codigo.getText() + "', '" 
                    + nombre.getText() + "', '" 
                    + fecha + "', '"
                    + genero +"', "
                    + carrera.getSelectedIndex() + ", '"
                    + intereses +"');";
                    
            stmt.executeUpdate(sql);
  
            conexion.close();
        } catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_insertarActionPerformed

    private void carreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carreraActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_carreraActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        try{
            Connection conexion = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/ejercicioSwing", // URL BD
                "root",  // usuario de MySQL
                ""   // contraseña de MySQL
            );
            String x = codigo.getText();
            
            Statement stmt = conexion.createStatement();
            String sql = "DELETE FROM estudiante WHERE codigo = "+x+";";
                    
            stmt.executeUpdate(sql);
            conexion.close();
        } catch (Exception e){
            e.printStackTrace();
        }

        
        
    }//GEN-LAST:event_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TallerBBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TallerBBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TallerBBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TallerBBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        boolean flag=false;
        try{
            Connection conexion = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/ejercicioSwing", // URL BD
                "root",  // usuario de MySQL
                ""   // contraseña de MySQL
            );
            System.out.println("Conexion establecida");            
            conexion.close();
            flag=true;
        } catch (Exception e){
            e.printStackTrace();
        }
        


        if(flag){
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new TallerBBDD().setVisible(true);
                }
            });
        }else{
            JOptionPane.showMessageDialog(
            null, 
            "No se pudo conectar con la base de datos\nejercicioSwing", 
            "Error", 
            JOptionPane.ERROR_MESSAGE
        );

        
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel botones;
    private javax.swing.JButton buscar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> carrera;
    private java.awt.Label carreraTexto;
    private java.awt.Panel checkbox;
    private javax.swing.JTextField codigo;
    private java.awt.Label codigoTexto;
    private java.awt.Checkbox danza;
    private java.awt.Checkbox deportes;
    private javax.swing.JButton eliminar;
    private javax.swing.JRadioButton femenino;
    private javax.swing.JButton insertar;
    private java.awt.Label intereses;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private java.awt.Checkbox lectura;
    private javax.swing.JButton limpiar;
    private javax.swing.JRadioButton masculino;
    private javax.swing.JButton modificar;
    private java.awt.Checkbox musica;
    private java.awt.Label nacimientoTexto;
    private javax.swing.JTextField nombre;
    private java.awt.Label nombreTexto;
    private java.awt.Checkbox teatro;
    private java.awt.Label titulo;
    private java.awt.Checkbox videojuegos;
    // End of variables declaration//GEN-END:variables
}
